### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Hasumi-Uehara** [Hasumi-Uehara/protospace-32482#1]
# URL
https://protospace-32482.herokuapp.com/

よろしくお願いします☺️

**Comment by hiraoka1102** [comment]
Hasumi-Ueharaさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
"プロトタイプ投稿機能"誤った情報では、そのページに留まる
→こちら情報が間違っていた場合、正常に弾いてはいるのですが「そのページ」ではなく「トップページ」に遷移されました！


修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by hiraoka1102** [comment]
Hasumi-Ueharaさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
